Use 'unsigned int' instead of 'uint'
The latter isn't defined on musl libc.

In file included from /home/pmos/build/src/qtmir-824e8b5bf92c2374d331af99e6845ea594ec0ea5/src/platforms/mirserver/miral/persist_display_config.cpp:21:
/home/pmos/build/src/qtmir-824e8b5bf92c2374d331af99e6845ea594ec0ea5/include/qtmir/miral/display_configuration_storage.h:35:25: error: 'uint' was not declared in this scope; did you mean 'int'?
   35 |     mir::optional_value<uint> clone_output_index;
      |                         ^~~~
      |                         int
/home/pmos/build/src/qtmir-824e8b5bf92c2374d331af99e6845ea594ec0ea5/include/qtmir/miral/display_configuration_storage.h:35:29: error: template argument 1 is invalid
   35 |     mir::optional_value<uint> clone_output_index;
      |                             ^